### PR TITLE
Recruitment page form

### PR DESCRIPTION
**Pull request by JuanitaCathy**
Fixes issue #7 

Created a basic form in the recruitment page with validation.

### CODE REVIEW

**Comment by prernamittal** [comment]
Hey, could you please check out the UI of this page again? The navbar isn't coming properly and the UI is yellow but we're following a blue color scheme.

**Comment by JuanitaCathy** [comment]
yes, the style.css was done after i created a PR

**Comment by JuanitaCathy** [comment]
> Hey, could you please check out the UI of this page again? The navbar isn't coming properly and the UI is yellow but we're following a blue color scheme.

yes, the style.css was done after i created a PR

**Comment by JuanitaCathy** [comment]
I'll link the stylesheet in the code, apologies

**Pull request merged**
